/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Nitropc
 */
public class VistaVagos extends javax.swing.JFrame {

    /**
     * Creates new form VistaVagos
     */
    public VistaVagos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUsuario2 = new javax.swing.JPanel();
        etiquetaApellidos2 = new javax.swing.JLabel();
        etiquetaNombres2 = new javax.swing.JLabel();
        etiquetaCI2 = new javax.swing.JLabel();
        textoContraseñaUsuario1 = new javax.swing.JTextField();
        textoNombreUsuario1 = new javax.swing.JTextField();
        botonNuevoUsuario1 = new javax.swing.JButton();
        botonSesion1 = new javax.swing.JButton();
        etiquetaPanelUsuario4 = new javax.swing.JLabel();
        panelUsuario3 = new javax.swing.JPanel();
        etiquetaApellidos3 = new javax.swing.JLabel();
        etiquetaNombres3 = new javax.swing.JLabel();
        etiquetaCI3 = new javax.swing.JLabel();
        textoContraseñaUsuario2 = new javax.swing.JTextField();
        textoNombreUsuario2 = new javax.swing.JTextField();
        botonNuevoUsuario2 = new javax.swing.JButton();
        botonSesion2 = new javax.swing.JButton();
        etiquetaPanelUsuario5 = new javax.swing.JLabel();
        etiquetaPanelUsuario3 = new javax.swing.JLabel();
        panelUsuario = new javax.swing.JPanel();
        etiquetaApellidos = new javax.swing.JLabel();
        etiquetaContraseñaUsuario = new javax.swing.JLabel();
        etiquetaNombreUsuario = new javax.swing.JLabel();
        textoNombreUsuario = new javax.swing.JTextField();
        botonNuevoUsuario = new javax.swing.JButton();
        botonSesion = new javax.swing.JButton();
        textoContraseñaUsuario = new javax.swing.JPasswordField();
        etiquetaPanelUsuario = new javax.swing.JLabel();
        etiquetaPanelReseña = new javax.swing.JLabel();
        panelUsuario1 = new javax.swing.JPanel();
        etiquetaApellidos1 = new javax.swing.JLabel();
        etiquetaReseñaComentario = new javax.swing.JLabel();
        botonReseñaSubirComentario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoReseñeaComentario = new javax.swing.JTextArea();
        etiquetaPanelEdificio = new javax.swing.JLabel();
        panelUsuario4 = new javax.swing.JPanel();
        etiquetaApellidos4 = new javax.swing.JLabel();
        etiquetaNombreEdificio = new javax.swing.JLabel();
        textoEdificioNombre = new javax.swing.JTextField();
        botonEdificioListarReseñas = new javax.swing.JButton();
        botonEdificioListarEdificio = new javax.swing.JButton();

        panelUsuario2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        etiquetaNombres2.setText("Contraseña");

        etiquetaCI2.setText("Nombre:");

        botonNuevoUsuario1.setText("Nuevo");

        botonSesion1.setText("Iniciar Sesión");

        etiquetaPanelUsuario4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaPanelUsuario4.setText("Usuario");

        panelUsuario3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        etiquetaNombres3.setText("Contraseña");

        etiquetaCI3.setText("Nombre:");

        botonNuevoUsuario2.setText("Nuevo");

        botonSesion2.setText("Iniciar Sesión");

        etiquetaPanelUsuario5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaPanelUsuario5.setText("Usuario");

        javax.swing.GroupLayout panelUsuario3Layout = new javax.swing.GroupLayout(panelUsuario3);
        panelUsuario3.setLayout(panelUsuario3Layout);
        panelUsuario3Layout.setHorizontalGroup(
            panelUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuario3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaCI3)
                    .addComponent(etiquetaNombres3)
                    .addComponent(etiquetaApellidos3))
                .addGap(40, 40, 40)
                .addGroup(panelUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textoContraseñaUsuario2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(textoNombreUsuario2))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelUsuario3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(botonSesion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(botonNuevoUsuario2)
                .addGap(54, 54, 54))
            .addGroup(panelUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelUsuario3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(etiquetaPanelUsuario5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelUsuario3Layout.setVerticalGroup(
            panelUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuario3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panelUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNombreUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaCI3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoContraseñaUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaNombres3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevoUsuario2)
                    .addComponent(botonSesion2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaApellidos3)
                .addGap(28, 28, 28))
            .addGroup(panelUsuario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelUsuario3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(etiquetaPanelUsuario5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelUsuario2Layout = new javax.swing.GroupLayout(panelUsuario2);
        panelUsuario2.setLayout(panelUsuario2Layout);
        panelUsuario2Layout.setHorizontalGroup(
            panelUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuario2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaCI2)
                    .addComponent(etiquetaNombres2)
                    .addComponent(etiquetaApellidos2))
                .addGap(40, 40, 40)
                .addGroup(panelUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textoContraseñaUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(textoNombreUsuario1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelUsuario2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(botonSesion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(botonNuevoUsuario1)
                .addGap(54, 54, 54))
            .addGroup(panelUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelUsuario2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(etiquetaPanelUsuario4)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(panelUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelUsuario2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelUsuario2Layout.setVerticalGroup(
            panelUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuario2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panelUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNombreUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaCI2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoContraseñaUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaNombres2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevoUsuario1)
                    .addComponent(botonSesion1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaApellidos2)
                .addGap(28, 28, 28))
            .addGroup(panelUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelUsuario2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(etiquetaPanelUsuario4)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(panelUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelUsuario2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        etiquetaPanelUsuario3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaPanelUsuario3.setText("Usuario");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        etiquetaContraseñaUsuario.setText("Contraseña:");

        etiquetaNombreUsuario.setText("Nombre:");

        botonNuevoUsuario.setText("Nuevo");
        botonNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoUsuarioActionPerformed(evt);
            }
        });

        botonSesion.setText("Iniciar Sesión");
        botonSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaNombreUsuario)
                    .addComponent(etiquetaContraseñaUsuario)
                    .addComponent(etiquetaApellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoContraseñaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(textoNombreUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(botonSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(botonNuevoUsuario)
                .addGap(54, 54, 54))
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaNombreUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaContraseñaUsuario)
                    .addComponent(textoContraseñaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevoUsuario)
                    .addComponent(botonSesion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaApellidos)
                .addGap(28, 28, 28))
        );

        etiquetaPanelUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaPanelUsuario.setText("Usuario");

        etiquetaPanelReseña.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaPanelReseña.setText("Reseña");

        panelUsuario1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        etiquetaReseñaComentario.setText("Comentario:");

        botonReseñaSubirComentario.setText("Subir Comentario");
        botonReseñaSubirComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReseñaSubirComentarioActionPerformed(evt);
            }
        });

        campoReseñeaComentario.setColumns(20);
        campoReseñeaComentario.setRows(5);
        jScrollPane1.setViewportView(campoReseñeaComentario);

        javax.swing.GroupLayout panelUsuario1Layout = new javax.swing.GroupLayout(panelUsuario1);
        panelUsuario1.setLayout(panelUsuario1Layout);
        panelUsuario1Layout.setHorizontalGroup(
            panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuario1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsuario1Layout.createSequentialGroup()
                        .addComponent(etiquetaReseñaComentario)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuario1Layout.createSequentialGroup()
                        .addGap(0, 86, Short.MAX_VALUE)
                        .addComponent(botonReseñaSubirComentario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etiquetaApellidos1)
                        .addGap(335, 335, 335))))
        );
        panelUsuario1Layout.setVerticalGroup(
            panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuario1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaReseñaComentario)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsuario1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(etiquetaApellidos1))
                    .addGroup(panelUsuario1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(botonReseñaSubirComentario)))
                .addGap(74, 74, 74))
        );

        etiquetaPanelEdificio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiquetaPanelEdificio.setText("Edificio");

        panelUsuario4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        etiquetaNombreEdificio.setText("Nombre:");

        botonEdificioListarReseñas.setText("Listar Reseñas");
        botonEdificioListarReseñas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEdificioListarReseñasActionPerformed(evt);
            }
        });

        botonEdificioListarEdificio.setText("Listar Edificio");
        botonEdificioListarEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEdificioListarEdificioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUsuario4Layout = new javax.swing.GroupLayout(panelUsuario4);
        panelUsuario4.setLayout(panelUsuario4Layout);
        panelUsuario4Layout.setHorizontalGroup(
            panelUsuario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuario4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUsuario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsuario4Layout.createSequentialGroup()
                        .addComponent(etiquetaApellidos4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelUsuario4Layout.createSequentialGroup()
                        .addGroup(panelUsuario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelUsuario4Layout.createSequentialGroup()
                                .addComponent(etiquetaNombreEdificio)
                                .addGap(31, 31, 31)
                                .addComponent(textoEdificioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelUsuario4Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(botonEdificioListarEdificio)
                                .addGap(18, 18, 18)
                                .addComponent(botonEdificioListarReseñas)))
                        .addContainerGap(21, Short.MAX_VALUE))))
        );
        panelUsuario4Layout.setVerticalGroup(
            panelUsuario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuario4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelUsuario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoEdificioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaNombreEdificio))
                .addGap(18, 18, 18)
                .addGroup(panelUsuario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEdificioListarEdificio)
                    .addComponent(botonEdificioListarReseñas))
                .addGap(22, 22, 22)
                .addComponent(etiquetaApellidos4)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaPanelUsuario)
                            .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiquetaPanelEdificio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(panelUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(etiquetaPanelReseña)
                    .addComponent(panelUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaPanelUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaPanelEdificio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(etiquetaPanelReseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonReseñaSubirComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReseñaSubirComentarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonReseñaSubirComentarioActionPerformed

    private void botonSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSesionActionPerformed

    private void botonNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNuevoUsuarioActionPerformed

    private void botonEdificioListarEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEdificioListarEdificioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEdificioListarEdificioActionPerformed

    private void botonEdificioListarReseñasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEdificioListarReseñasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEdificioListarReseñasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaVagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaVagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaVagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaVagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaVagos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEdificioListarEdificio;
    private javax.swing.JButton botonEdificioListarReseñas;
    private javax.swing.JButton botonNuevoUsuario;
    private javax.swing.JButton botonNuevoUsuario1;
    private javax.swing.JButton botonNuevoUsuario2;
    private javax.swing.JButton botonReseñaSubirComentario;
    private javax.swing.JButton botonSesion;
    private javax.swing.JButton botonSesion1;
    private javax.swing.JButton botonSesion2;
    private javax.swing.JTextArea campoReseñeaComentario;
    private javax.swing.JLabel etiquetaApellidos;
    private javax.swing.JLabel etiquetaApellidos1;
    private javax.swing.JLabel etiquetaApellidos2;
    private javax.swing.JLabel etiquetaApellidos3;
    private javax.swing.JLabel etiquetaApellidos4;
    private javax.swing.JLabel etiquetaCI2;
    private javax.swing.JLabel etiquetaCI3;
    private javax.swing.JLabel etiquetaContraseñaUsuario;
    private javax.swing.JLabel etiquetaNombreEdificio;
    private javax.swing.JLabel etiquetaNombreUsuario;
    private javax.swing.JLabel etiquetaNombres2;
    private javax.swing.JLabel etiquetaNombres3;
    private javax.swing.JLabel etiquetaPanelEdificio;
    private javax.swing.JLabel etiquetaPanelReseña;
    private javax.swing.JLabel etiquetaPanelUsuario;
    private javax.swing.JLabel etiquetaPanelUsuario3;
    private javax.swing.JLabel etiquetaPanelUsuario4;
    private javax.swing.JLabel etiquetaPanelUsuario5;
    private javax.swing.JLabel etiquetaReseñaComentario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelUsuario;
    private javax.swing.JPanel panelUsuario1;
    private javax.swing.JPanel panelUsuario2;
    private javax.swing.JPanel panelUsuario3;
    private javax.swing.JPanel panelUsuario4;
    private javax.swing.JPasswordField textoContraseñaUsuario;
    private javax.swing.JTextField textoContraseñaUsuario1;
    private javax.swing.JTextField textoContraseñaUsuario2;
    private javax.swing.JTextField textoEdificioNombre;
    private javax.swing.JTextField textoNombreUsuario;
    private javax.swing.JTextField textoNombreUsuario1;
    private javax.swing.JTextField textoNombreUsuario2;
    // End of variables declaration//GEN-END:variables
}
